version: "3"
services:
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gateways
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root

  gateway-manager-service:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
    restart: always

#    command: sh -c './wait-for mysql_db:3306 -- npm start'
